Increase webcam discovery timeout
I was consistently encountering the following error whenever I clicked
the SCAN QR CODE button:

> java.util.concurrent.TimeoutException: Webcams discovery timeout (1000 ms) has been exceeded

Not sure if it is a hardware or OS related issue, but when increasing
the timeout to 2 seconds I no longer encounter the error and it
successfully discovers the webcam.